const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Orbit,
		C3.Behaviors.Flash,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Orbit.Acts.SetSpeed,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Browser.Acts.Vibrate,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Exps.int
	];
};
self.C3_JsPropNameTable = [
	{teladog: 0},
	{Sprite3: 0},
	{Sólido: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{escolhapet: 0},
	{Centroohana: 0},
	{centrojoca: 0},
	{jocainvencivel: 0},
	{Órbita: 0},
	{Piscar: 0},
	{cabeçajoca: 0},
	{ohanacabeca: 0},
	{Projétil: 0},
	{DestruirForaDoLayout: 0},
	{carrapato: 0},
	{Toque: 0},
	{Sprite22: 0},
	{pulga: 0},
	{Sprite25: 0},
	{TxtPontos: 0},
	{Sprite6: 0},
	{botaoinvisivelohana: 0},
	{botaoinvisiveljoca: 0},
	{botaoplayinvisivel: 0},
	{Áudio: 0},
	{Sprite: 0},
	{telafinal: 0},
	{botaoinvisiveltentenovamente: 0},
	{Sprite7: 0},
	{coraçãolifevida: 0},
	{TextoPontuacao: 0},
	{botaoinvisivelcompartilhar: 0},
	{Navegador: 0},
	{telafinaltentenovamente: 0},
	{telapremiação: 0},
	{coraçãofixo: 0},
	{Sprite8: 0},
	{Velocidade_Ohana: 0},
	{pontosohana: 0},
	{perdervidaohana: 0},
	{Velocidade_joca: 0},
	{pontosjoca: 0},
	{perdervidajoca: 0},
	{mensagemwhatsapp: 0},
	{linkwaths: 0}
];

self.InstanceType = {
	teladog: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	escolhapet: class extends self.ISpriteInstance {},
	Centroohana: class extends self.ISpriteInstance {},
	centrojoca: class extends self.ISpriteInstance {},
	cabeçajoca: class extends self.ISpriteInstance {},
	ohanacabeca: class extends self.ISpriteInstance {},
	carrapato: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	pulga: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	TxtPontos: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	botaoinvisivelohana: class extends self.ISpriteInstance {},
	botaoinvisiveljoca: class extends self.ISpriteInstance {},
	botaoplayinvisivel: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	telafinal: class extends self.ISpriteInstance {},
	botaoinvisiveltentenovamente: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	coraçãolifevida: class extends self.ISpriteInstance {},
	TextoPontuacao: class extends self.ITextInstance {},
	botaoinvisivelcompartilhar: class extends self.ISpriteInstance {},
	Navegador: class extends self.IInstance {},
	telafinaltentenovamente: class extends self.ISpriteInstance {},
	telapremiação: class extends self.ISpriteInstance {},
	coraçãofixo: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {}
}